//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRACTICA1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public int ID_Movie { get; set; }
        public string MovieName { get; set; }
        public Nullable<int> Director_ID { get; set; }
        public Nullable<int> Genre_ID { get; set; }
    
        public virtual Directors Directors { private get; set; }
        public virtual Genres Genres { private get; set; }
    }
}
